<?php

namespace Container0x6DeKA;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WAHVzEUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wAHVzEU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wAHVzEU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\EvenementController::index' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\EvenementController::nePasParticiperEvenement' => ['privates', '.service_locator.bCdRQ_V', 'get_ServiceLocator_BCdRQVService', true],
            'App\\Controller\\EvenementController::new_edit' => ['privates', '.service_locator.EMuVimD', 'get_ServiceLocator_EMuVimDService', true],
            'App\\Controller\\EvenementController::nextEvents' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\EvenementController::participerEvenement' => ['privates', '.service_locator.bCdRQ_V', 'get_ServiceLocator_BCdRQVService', true],
            'App\\Controller\\EvenementController::show' => ['privates', '.service_locator.JFCU_Ej', 'get_ServiceLocator_JFCUEjService', true],
            'App\\Controller\\EvenementController::supprCommentaire' => ['privates', '.service_locator.HrDCg3Q', 'get_ServiceLocator_HrDCg3QService', true],
            'App\\Controller\\EvenementController::supprEvenement' => ['privates', '.service_locator.JFCU_Ej', 'get_ServiceLocator_JFCUEjService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\MembreController::index' => ['privates', '.service_locator.0OOzoxv', 'get_ServiceLocator_0OOzoxvService', true],
            'App\\Controller\\MembreController::new_editMembre' => ['privates', '.service_locator.SYNmfUk', 'get_ServiceLocator_SYNmfUkService', true],
            'App\\Controller\\MembreController::show' => ['privates', '.service_locator.0OOzoxv', 'get_ServiceLocator_0OOzoxvService', true],
            'App\\Controller\\MembreController::supprMembre' => ['privates', '.service_locator.N6BHFr1', 'get_ServiceLocator_N6BHFr1Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.Tj7FrpL', 'get_ServiceLocator_Tj7FrpLService', true],
            'App\\Controller\\RegistrationController::verifUser' => ['privates', '.service_locator.yoflbtf', 'get_ServiceLocator_YoflbtfService', true],
            'App\\Controller\\SecurityController::forgottenPassword' => ['privates', '.service_locator.t9aPEVW', 'get_ServiceLocator_T9aPEVWService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController::resetPassword' => ['privates', '.service_locator.kuUfZEq', 'get_ServiceLocator_KuUfZEqService', true],
            'App\\Controller\\UserController::editCurrentUser' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\UserController::supprUser' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\EvenementController:index' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\EvenementController:nePasParticiperEvenement' => ['privates', '.service_locator.bCdRQ_V', 'get_ServiceLocator_BCdRQVService', true],
            'App\\Controller\\EvenementController:new_edit' => ['privates', '.service_locator.EMuVimD', 'get_ServiceLocator_EMuVimDService', true],
            'App\\Controller\\EvenementController:nextEvents' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\EvenementController:participerEvenement' => ['privates', '.service_locator.bCdRQ_V', 'get_ServiceLocator_BCdRQVService', true],
            'App\\Controller\\EvenementController:show' => ['privates', '.service_locator.JFCU_Ej', 'get_ServiceLocator_JFCUEjService', true],
            'App\\Controller\\EvenementController:supprCommentaire' => ['privates', '.service_locator.HrDCg3Q', 'get_ServiceLocator_HrDCg3QService', true],
            'App\\Controller\\EvenementController:supprEvenement' => ['privates', '.service_locator.JFCU_Ej', 'get_ServiceLocator_JFCUEjService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\MembreController:index' => ['privates', '.service_locator.0OOzoxv', 'get_ServiceLocator_0OOzoxvService', true],
            'App\\Controller\\MembreController:new_editMembre' => ['privates', '.service_locator.SYNmfUk', 'get_ServiceLocator_SYNmfUkService', true],
            'App\\Controller\\MembreController:show' => ['privates', '.service_locator.0OOzoxv', 'get_ServiceLocator_0OOzoxvService', true],
            'App\\Controller\\MembreController:supprMembre' => ['privates', '.service_locator.N6BHFr1', 'get_ServiceLocator_N6BHFr1Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.Tj7FrpL', 'get_ServiceLocator_Tj7FrpLService', true],
            'App\\Controller\\RegistrationController:verifUser' => ['privates', '.service_locator.yoflbtf', 'get_ServiceLocator_YoflbtfService', true],
            'App\\Controller\\SecurityController:forgottenPassword' => ['privates', '.service_locator.t9aPEVW', 'get_ServiceLocator_T9aPEVWService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController:resetPassword' => ['privates', '.service_locator.kuUfZEq', 'get_ServiceLocator_KuUfZEqService', true],
            'App\\Controller\\UserController:editCurrentUser' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\UserController:supprUser' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\EvenementController::index' => '?',
            'App\\Controller\\EvenementController::nePasParticiperEvenement' => '?',
            'App\\Controller\\EvenementController::new_edit' => '?',
            'App\\Controller\\EvenementController::nextEvents' => '?',
            'App\\Controller\\EvenementController::participerEvenement' => '?',
            'App\\Controller\\EvenementController::show' => '?',
            'App\\Controller\\EvenementController::supprCommentaire' => '?',
            'App\\Controller\\EvenementController::supprEvenement' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\MembreController::index' => '?',
            'App\\Controller\\MembreController::new_editMembre' => '?',
            'App\\Controller\\MembreController::show' => '?',
            'App\\Controller\\MembreController::supprMembre' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifUser' => '?',
            'App\\Controller\\SecurityController::forgottenPassword' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::resetPassword' => '?',
            'App\\Controller\\UserController::editCurrentUser' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Controller\\UserController::supprUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\EvenementController:index' => '?',
            'App\\Controller\\EvenementController:nePasParticiperEvenement' => '?',
            'App\\Controller\\EvenementController:new_edit' => '?',
            'App\\Controller\\EvenementController:nextEvents' => '?',
            'App\\Controller\\EvenementController:participerEvenement' => '?',
            'App\\Controller\\EvenementController:show' => '?',
            'App\\Controller\\EvenementController:supprCommentaire' => '?',
            'App\\Controller\\EvenementController:supprEvenement' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\MembreController:index' => '?',
            'App\\Controller\\MembreController:new_editMembre' => '?',
            'App\\Controller\\MembreController:show' => '?',
            'App\\Controller\\MembreController:supprMembre' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifUser' => '?',
            'App\\Controller\\SecurityController:forgottenPassword' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:resetPassword' => '?',
            'App\\Controller\\UserController:editCurrentUser' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:show' => '?',
            'App\\Controller\\UserController:supprUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
