<?php

namespace ContainerLM5Gix7;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XmtPN88Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xmtPN88' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xmtPN88'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\EntrainementController::listEntrainements' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EvenementController::index' => ['privates', '.service_locator.zoVzhCf', 'get_ServiceLocator_ZoVzhCfService', true],
            'App\\Controller\\EvenementController::nePlusParticiper' => ['privates', '.service_locator.iRKfnRe', 'get_ServiceLocator_IRKfnReService', true],
            'App\\Controller\\EvenementController::new_edit' => ['privates', '.service_locator.EMuVimD', 'get_ServiceLocator_EMuVimDService', true],
            'App\\Controller\\EvenementController::participer' => ['privates', '.service_locator.JFCU_Ej', 'get_ServiceLocator_JFCUEjService', true],
            'App\\Controller\\EvenementController::show' => ['privates', '.service_locator.JFCU_Ej', 'get_ServiceLocator_JFCUEjService', true],
            'App\\Controller\\EvenementController::supprCommentaire' => ['privates', '.service_locator.HrDCg3Q', 'get_ServiceLocator_HrDCg3QService', true],
            'App\\Controller\\EvenementController::supprEvenement' => ['privates', '.service_locator.JFCU_Ej', 'get_ServiceLocator_JFCUEjService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.Tj7FrpL', 'get_ServiceLocator_Tj7FrpLService', true],
            'App\\Controller\\RegistrationController::registerMembre' => ['privates', '.service_locator.Tj7FrpL', 'get_ServiceLocator_Tj7FrpLService', true],
            'App\\Controller\\RegistrationController::verifUser' => ['privates', '.service_locator.yoflbtf', 'get_ServiceLocator_YoflbtfService', true],
            'App\\Controller\\SecurityController::forgottenPassword' => ['privates', '.service_locator.t9aPEVW', 'get_ServiceLocator_T9aPEVWService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController::resetPassword' => ['privates', '.service_locator.kuUfZEq', 'get_ServiceLocator_KuUfZEqService', true],
            'App\\Controller\\UserController::editCurrentUser' => ['privates', '.service_locator.pbtqkCT', 'get_ServiceLocator_PbtqkCTService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\UserController::supprUser' => ['privates', '.service_locator.d_UY3kt', 'get_ServiceLocator_DUY3ktService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\EntrainementController:listEntrainements' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EvenementController:index' => ['privates', '.service_locator.zoVzhCf', 'get_ServiceLocator_ZoVzhCfService', true],
            'App\\Controller\\EvenementController:nePlusParticiper' => ['privates', '.service_locator.iRKfnRe', 'get_ServiceLocator_IRKfnReService', true],
            'App\\Controller\\EvenementController:new_edit' => ['privates', '.service_locator.EMuVimD', 'get_ServiceLocator_EMuVimDService', true],
            'App\\Controller\\EvenementController:participer' => ['privates', '.service_locator.JFCU_Ej', 'get_ServiceLocator_JFCUEjService', true],
            'App\\Controller\\EvenementController:show' => ['privates', '.service_locator.JFCU_Ej', 'get_ServiceLocator_JFCUEjService', true],
            'App\\Controller\\EvenementController:supprCommentaire' => ['privates', '.service_locator.HrDCg3Q', 'get_ServiceLocator_HrDCg3QService', true],
            'App\\Controller\\EvenementController:supprEvenement' => ['privates', '.service_locator.JFCU_Ej', 'get_ServiceLocator_JFCUEjService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.Tj7FrpL', 'get_ServiceLocator_Tj7FrpLService', true],
            'App\\Controller\\RegistrationController:registerMembre' => ['privates', '.service_locator.Tj7FrpL', 'get_ServiceLocator_Tj7FrpLService', true],
            'App\\Controller\\RegistrationController:verifUser' => ['privates', '.service_locator.yoflbtf', 'get_ServiceLocator_YoflbtfService', true],
            'App\\Controller\\SecurityController:forgottenPassword' => ['privates', '.service_locator.t9aPEVW', 'get_ServiceLocator_T9aPEVWService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController:resetPassword' => ['privates', '.service_locator.kuUfZEq', 'get_ServiceLocator_KuUfZEqService', true],
            'App\\Controller\\UserController:editCurrentUser' => ['privates', '.service_locator.pbtqkCT', 'get_ServiceLocator_PbtqkCTService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\UserController:supprUser' => ['privates', '.service_locator.d_UY3kt', 'get_ServiceLocator_DUY3ktService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\EntrainementController::listEntrainements' => '?',
            'App\\Controller\\EvenementController::index' => '?',
            'App\\Controller\\EvenementController::nePlusParticiper' => '?',
            'App\\Controller\\EvenementController::new_edit' => '?',
            'App\\Controller\\EvenementController::participer' => '?',
            'App\\Controller\\EvenementController::show' => '?',
            'App\\Controller\\EvenementController::supprCommentaire' => '?',
            'App\\Controller\\EvenementController::supprEvenement' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::registerMembre' => '?',
            'App\\Controller\\RegistrationController::verifUser' => '?',
            'App\\Controller\\SecurityController::forgottenPassword' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::resetPassword' => '?',
            'App\\Controller\\UserController::editCurrentUser' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Controller\\UserController::supprUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\EntrainementController:listEntrainements' => '?',
            'App\\Controller\\EvenementController:index' => '?',
            'App\\Controller\\EvenementController:nePlusParticiper' => '?',
            'App\\Controller\\EvenementController:new_edit' => '?',
            'App\\Controller\\EvenementController:participer' => '?',
            'App\\Controller\\EvenementController:show' => '?',
            'App\\Controller\\EvenementController:supprCommentaire' => '?',
            'App\\Controller\\EvenementController:supprEvenement' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:registerMembre' => '?',
            'App\\Controller\\RegistrationController:verifUser' => '?',
            'App\\Controller\\SecurityController:forgottenPassword' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:resetPassword' => '?',
            'App\\Controller\\UserController:editCurrentUser' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:show' => '?',
            'App\\Controller\\UserController:supprUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
