<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSw9PxE5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSw9PxE5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSw9PxE5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSw9PxE5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSw9PxE5\App_KernelDevDebugContainer([
    'container.build_hash' => 'Sw9PxE5',
    'container.build_id' => '17872536',
    'container.build_time' => 1729838782,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSw9PxE5');
