<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQyurv7V\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQyurv7V/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQyurv7V.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQyurv7V\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQyurv7V\App_KernelDevDebugContainer([
    'container.build_hash' => 'Qyurv7V',
    'container.build_id' => 'bed05609',
    'container.build_time' => 1722587124,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQyurv7V');
